name: MERN CI/CD Pipeline

on:
   push:
      branches:
         - deploy
   pull_request:
      branches:
         - deploy

jobs:
   check-changes:
      runs-on: ubuntu-latest
      outputs:
         backend_changed: ${{steps.backend_changed.outputs.backend_changed}}
         frontend_changed: ${{steps.frontend_changed.outputs.frontend_changed}}
      steps:
         - name: Checkout Code
           uses: actions/checkout@v4

         - name: Check for changes in backend
           id: backend_changed
           uses: dorny/paths-filter@v3
           with:
              filters: |
                 backend:
                   - 'backend/**'

         - name: Check for changes in frontend
           id: frontend_changed
           uses: dorny/paths-filter@v3
           with:
              filters: |
                 frontend:
                   - 'frontend/**'

   backend:
      runs-on: ubuntu-latest
      needs: check-changes
      if: needs.check-changes.outputs.backend_changed == 'true'
      steps:
         - name: Set up backend
           run: |
              echo "Setting up backend..."
              # Add any additional setup commands here

   frontend:
      runs-on: ubuntu-latest
      needs: check-changes
      if: needs.check-changes.outputs.frontend_changed == 'true'
      steps:
         - name: Set up frontend
           run: |
              echo "Setting up frontend..."
              # Add any additional setup commands here
