name: MERN CI/CD Pipeline

on:
   push:
      branches:
         - deploy
   pull_request:
      branches:
         - deploy

jobs:
   check-changes:
      runs-on: ubuntu-latest
      outputs:
         backend_changed: ${{ steps.changes.outputs.backend }}
         frontend_changed: ${{ steps.changes.outputs.frontend }}
      steps:
         - name: Checkout Code
           uses: actions/checkout@v4

         - name: Check for changes
           id: changes
           uses: dorny/paths-filter@v3
           with:
              filters: |
                 backend:
                   - 'backend/**'
                 frontend:
                   - 'frontend/**'

         - name: Debug outputs
           run: |
              echo "Backend changed: ${{ steps.changes.outputs.backend }}"
              echo "Frontend changed: ${{ steps.changes.outputs.frontend }}"

   backend:
      runs-on: ubuntu-latest
      needs: check-changes
      if: needs.check-changes.outputs.backend_changed == 'true'
      steps:
         - name: Set up backend
           run: |
              echo "Setting up backend..."
              echo "Backend changed: ${{ needs.check-changes.outputs.backend_changed }}"
              echo "Frontend changed: ${{ needs.check-changes.outputs.frontend_changed }}"

   frontend:
      runs-on: ubuntu-latest
      needs: check-changes
      if: needs.check-changes.outputs.frontend_changed == 'true'
      steps:
         - name: Set up frontend
           run: |
              echo "Setting up frontend..."
              echo "Backend changed: ${{ needs.check-changes.outputs.backend_changed }}"
              echo "Frontend changed: ${{ needs.check-changes.outputs.frontend_changed }}"
